# Generated by Django 3.1a1 on 2024-08-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('denominacion', models.CharField(max_length=50)),
                ('forma_farmaceutica', models.CharField(choices=[('TR1', 'TR1'), ('TR2', 'TR2'), ('TR3', 'TR3'), ('TR4', 'TR4'), ('TR5', 'TR5')], default='TR1', max_length=3)),
                ('dosis', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('unidad_dosis', models.CharField(choices=[('TR1', 'TR1'), ('TR2', 'TR2'), ('TR3', 'TR3'), ('TR4', 'TR4'), ('TR5', 'TR5')], default='TR1', max_length=3)),
                ('reg_sanitario', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('via_administración', models.CharField(choices=[('TR1', 'TR1'), ('TR2', 'TR2'), ('TR3', 'TR3'), ('TR4', 'TR4'), ('TR5', 'TR5')], default='TR1', max_length=3)),
                ('fecha_vencimiento', models.DateField(default='01/01/1960')),
                ('unidades_empaque', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True)),
                ('Laboratorio_fabricante', models.CharField(max_length=50)),
                ('historial', models.JSONField(default=dict)),
            ],
        ),
    ]
