# Generated by Django 3.1a1 on 2024-08-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='medicamento',
        ),
    ]
