# Generated by Django 3.1a1 on 2024-08-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20240808_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='cantidad',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(choices=[('tableta', 'tableta'), ('capsula', 'cápsula'), ('suspension', 'suspensión'), ('inyectable', 'solución inyectable')], default='tableta', max_length=30),
        ),
    ]
