# Generated by Django 3.1a1 on 2024-08-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20240809_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='unidad_dosis',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='precentacion_farmaceutica',
            field=models.CharField(choices=[('FRASCO', 'FRASCO'), ('VIAL', 'VIAL'), ('AMPOLLA', 'AMPOLLA'), ('BLISTER', 'BLISTER'), ('JERINGA', 'JERINGA PRELLENA')], default='BLISTER', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='dosis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_vencimiento',
            field=models.DateField(default='31/01/2026'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(choices=[('TABLETA', 'TABLETA'), ('CAPSULA', 'CAPSULA'), ('SUSPENSION', 'SUSPENSION'), ('INYECTABLE', 'SOLUCION INYECTABLE')], default='TABLETA', max_length=30),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='unidades_empaque',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='via_administración',
            field=models.CharField(choices=[('ORAL', 'ORAL'), ('INTRAVENOSA', 'INTRAVENOSA'), ('TOPICA', 'TOPICA,'), ('SUBLINGUAL', 'SUBLINGUAL'), ('VAGINAL', 'VAGINAL'), ('PARENTERAL', 'PARENTERAL'), ('INTRAMUSCULAR', 'INTRAMUSCULAR'), ('NASAL', 'NASAL'), ('OFTALMICA', 'OFTALMICA'), ('OTICA', 'OTICA')], default='oral', max_length=30),
        ),
    ]
