# Generated by Django 3.1a1 on 2024-08-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20240809_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_vencimiento',
            field=models.DateField(default='2025-04-09'),
        ),
    ]
