# Generated by Django 3.1a1 on 2024-08-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20240809_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='via_administración',
            field=models.CharField(choices=[('Tabla', 'Codigo'), ('ViaAdministracion', 'AU'), ('ViaAdministracion', 'BU'), ('ViaAdministracion', 'CA'), ('ViaAdministracion', 'CE'), ('ViaAdministracion', 'CO'), ('ViaAdministracion', 'DE'), ('ViaAdministracion', 'ED'), ('ViaAdministracion', 'ES'), ('ViaAdministracion', 'HD'), ('ViaAdministracion', 'HE'), ('ViaAdministracion', 'IA'), ('ViaAdministracion', 'IB'), ('ViaAdministracion', 'IC'), ('ViaAdministracion', 'ID'), ('ViaAdministracion', 'IE'), ('ViaAdministracion', 'IF'), ('ViaAdministracion', 'IG'), ('ViaAdministracion', 'IH'), ('ViaAdministracion', 'II'), ('ViaAdministracion', 'IK'), ('ViaAdministracion', 'IL'), ('ViaAdministracion', 'IM'), ('ViaAdministracion', 'IN'), ('ViaAdministracion', 'IO'), ('ViaAdministracion', 'IP'), ('ViaAdministracion', 'IR'), ('ViaAdministracion', 'IS'), ('ViaAdministracion', 'IT'), ('ViaAdministracion', 'IU'), ('ViaAdministracion', 'IV'), ('ViaAdministracion', 'IY'), ('ViaAdministracion', 'IZ'), ('ViaAdministracion', 'LE'), ('ViaAdministracion', 'LY'), ('ViaAdministracion', 'MD'), ('ViaAdministracion', 'ME'), ('ViaAdministracion', 'MP'), ('ViaAdministracion', 'OF'), ('ViaAdministracion', 'OT'), ('ViaAdministracion', 'PA'), ('ViaAdministracion', 'PE'), ('ViaAdministracion', 'PI'), ('ViaAdministracion', 'PN'), ('ViaAdministracion', 'PO'), ('ViaAdministracion', 'PR'), ('ViaAdministracion', 'PT'), ('ViaAdministracion', 'RB'), ('ViaAdministracion', 'RQ'), ('ViaAdministracion', 'SC'), ('ViaAdministracion', 'SL'), ('ViaAdministracion', 'SP'), ('ViaAdministracion', 'SY'), ('ViaAdministracion', 'TC'), ('ViaAdministracion', 'TD'), ('ViaAdministracion', 'TE'), ('ViaAdministracion', 'TM'), ('ViaAdministracion', 'TO'), ('ViaAdministracion', 'TP'), ('ViaAdministracion', 'TR'), ('ViaAdministracion', 'UR'), ('ViaAdministracion', 'VA'), ('ViaAdministracion', 'YL')], default='PO', max_length=50),
        ),
    ]
