# Generated by Django 3.1a1 on 2024-09-08 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0010_auto_20240819_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='historial',
        ),
        migrations.CreateModel(
            name='Historicalmedicamento',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=0, default=0, max_digits=11)),
                ('denominacion', models.CharField(max_length=50)),
                ('precentacion_farmaceutica', models.CharField(choices=[('FRASCO', 'FRASCO'), ('VIAL', 'VIAL'), ('AMPOLLA', 'AMPOLLA'), ('BLISTER', 'BLISTER'), ('JERINGA', 'JERINGA PRELLENA')], default='BLISTER', max_length=30)),
                ('forma_farmaceutica', models.CharField(choices=[('CB', 'CAPSULA BLANDA'), ('CD', 'CAPSULA DURA'), ('CE', 'CAPSULAS DE LIBERACION RETARDADA'), ('CM', 'CAPSULAS DE LIBERACION PROLONGADA'), ('DD', 'SISTEMAS TRANSDERMICO'), ('DI', 'S  DISPOSITIVOS INTRAUTERINOS'), ('DO', 'SISTEMA OCULAR'), ('DV', 'S  ANILLOS VAGINALES'), ('EM', 'EMULSIONES'), ('ET', 'CREMAS'), ('GA', 'GASES'), ('GB', 'GLOBULOS'), ('GE', 'GRANULADOS EFERVECENTES'), ('GL', 'ESPUMAS'), ('GN', 'GRANULADOS'), ('GS', 'GELES'), ('HS', 'SOLUCION ESTERIL PARA HEMODIALISIS'), ('IP', 'IMPLANTES'), ('MO', 'OVULOS'), ('MS', 'SUPOSITORIOS'), ('NB', 'MEDICAMENTOS CON DISPOSITIVO MECANICO PARA ADMIN  PRINC ACTIVO'), ('PE', 'POLVOS EFERVECENTES'), ('PL', 'POLVO LIOFILIZADO'), ('PO', 'POLVOS'), ('SCL', 'SIN CLASIFICAR'), ('SH', 'SOLUCIONES'), ('SI', 'SUSPENSIONES  PARA NEBULIZADORES O INHALADORES'), ('SN', 'SOLUCIONES PARA NEBULIZADORES O INHALADORES'), ('SS', 'SUSPENSIONES'), ('ST', 'TINTURAS'), ('SV', 'SOLUCION VAGINAL'), ('TC', 'TABLETA DE LIBERACION CONTROLADA'), ('TD', 'TABLETA DISPERSABLE'), ('TE', 'TABLETA EFERVECENTE'), ('TI', 'TIRAS'), ('TM', 'TABLETA MASTICABLE'), ('TN', 'TABLETAS CON O SIN RECUBR  QUE NO MODIFIQUEN LIBERACION FARMACO'), ('TO', 'TABLETA ORODISPERSABLE'), ('TR', 'TABLETAS DE LIBERACI N RETARDADA'), ('TS', 'TABLETAS DE LIBERACI N SOSTENIDA'), ('UO', 'UNG ENTO OFTALMICO')], default='TN', max_length=30)),
                ('dosis', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_sanitario', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('via_administración', models.CharField(choices=[('AU', 'INTRA AURAL'), ('BU', 'BUCAL'), ('CA', 'INTRA CORPUS CAVERNOSUM'), ('CE', 'INTRACEREBRAL'), ('CO', 'CONJUNTIVAL'), ('DE', 'DENTAL'), ('ED', 'EPIDURAL'), ('ES', 'ENDOSINUSAL'), ('HD', 'HEMODIALISIS'), ('HE', 'INTRAHEPATICA'), ('IA', 'INTRA ARTERIAL'), ('IB', 'INTRAVESICAL'), ('IC', 'INTRA CARDIAC'), ('ID', 'INTRADERMAL'), ('IE', 'INTRACAVERNOSA'), ('IF', 'INFILTRATIVA   BLOQUEOS'), ('IG', 'IRRIGACI N'), ('IH', 'INHALACION'), ('II', 'INFUSI N INTRAVENOSA'), ('IK', 'INTRAVASCULAR EN HEMODI LISIS'), ('IL', 'INTRAPLEURAL'), ('IM', 'INTRAMUSCULAR'), ('IN', 'INTRANASAL'), ('IO', 'INTRAOCULAR'), ('IP', 'INTRAPERITONEAL'), ('IR', 'INTRA ARTICULAR'), ('IS', 'INSUFLACION'), ('IT', 'INTRATECAL'), ('IU', 'INTRAUTERINA'), ('IV', 'INTRAVENOSA'), ('IY', 'INFILTRATIVA   LOCAL'), ('IZ', 'INFILTRATIVA   EPIDURAL'), ('LE', 'INTRALESIONAL'), ('LY', 'INTRALINFATICA'), ('MD', 'INTRAMEDULAR  MEDULA DEL HUESO'), ('ME', 'INTRAMENINGEA'), ('MP', 'IMPLANTE'), ('OF', 'OFTALMICA'), ('OT', 'OTICO AURICULAR'), ('PA', 'PERIARTICULAR'), ('PE', 'PERICARDIAL'), ('PI', 'PERFUSION INTRAVENOSA'), ('PN', 'PERINEURAL'), ('PO', 'ORAL'), ('PR', 'RECTAL'), ('PT', 'PARENTERAL'), ('RB', 'RETROBULBAR'), ('RQ', 'RAQUIDEA'), ('SC', 'SUBCUTANEA'), ('SL', 'SUBLINGUAL'), ('SP', 'INTRAESPINAL'), ('SY', 'SISTEMICA  SI LA RUTA NO ES ES'), ('TC', 'T PICA OCULAR'), ('TD', 'TRANSDERMAL'), ('TE', 'TABLETAS CON CUBIERTA ENT RICA'), ('TM', 'TRANSMAMARIA'), ('TO', 'TOPICA  EXTERNA'), ('TP', 'TRANSPLACENTAL'), ('TR', 'INTRATRAQUEAL'), ('UR', 'URETRAL'), ('VA', 'VAGINAL'), ('YL', 'INTRACEREBROVENTRICULAR')], default='PO', max_length=50)),
                ('fecha_vencimiento', models.DateField(default='2025-04-09')),
                ('unidades_empaque', models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=3, null=True)),
                ('Laboratorio_fabricante', models.CharField(max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical medicamento',
                'verbose_name_plural': 'historical medicamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
