# Generated by Django 3.1a1 on 2024-09-13 23:46

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20240908_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('new_continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.continent')),
                ('new_country', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='new_continent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='inventario.country')),
            ],
        ),
    ]
