# Generated by Django 3.1a1 on 2024-09-14 03:30

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_continent_country_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Via_administracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalmedicamento',
            name='forma_farmaceutica',
        ),
        migrations.RemoveField(
            model_name='historicalmedicamento',
            name='via_administración',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='forma_farmaceutica',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='via_administración',
        ),
        migrations.CreateModel(
            name='Forma_farmaceutica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('via_administracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.via_administracion')),
            ],
        ),
        migrations.AddField(
            model_name='historicalmedicamento',
            name='nueva_forma_farmaceutica',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='nueva_via_administracion', chained_model_field='via_administracion', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.forma_farmaceutica'),
        ),
        migrations.AddField(
            model_name='historicalmedicamento',
            name='nueva_via_administracion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.via_administracion'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='nueva_forma_farmaceutica',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='nueva_via_administracion', chained_model_field='via_administracion', default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.forma_farmaceutica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicamento',
            name='nueva_via_administracion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.via_administracion'),
            preserve_default=False,
        ),
    ]
