# Generated by Django 3.1a1 on 2024-09-14 12:27

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20240913_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmedicamento',
            name='nueva_forma_farmaceutica',
        ),
        migrations.RemoveField(
            model_name='forma_farmaceutica',
            name='via_administracion',
        ),
        migrations.AddField(
            model_name='forma_farmaceutica',
            name='via_administracion',
            field=models.ManyToManyField(to='inventario.Via_administracion'),
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='nueva_forma_farmaceutica',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='nueva_forma_farmaceutica',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='nueva_via_administracion', chained_model_field='via_administracion', to='inventario.Forma_farmaceutica'),
        ),
    ]
