# Generated by Django 3.1a1 on 2024-09-14 12:30

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20240914_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmedicamento',
            name='nueva_forma_farmaceutica',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='nueva_via_administracion', chained_model_field='via_administracion', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', show_all=True, to='inventario.forma_farmaceutica'),
        ),
        migrations.RemoveField(
            model_name='forma_farmaceutica',
            name='via_administracion',
        ),
        migrations.AddField(
            model_name='forma_farmaceutica',
            name='via_administracion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.via_administracion'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='nueva_forma_farmaceutica',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='nueva_forma_farmaceutica',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='nueva_via_administracion', chained_model_field='via_administracion', default=0, on_delete=django.db.models.deletion.CASCADE, show_all=True, to='inventario.forma_farmaceutica'),
            preserve_default=False,
        ),
    ]
