# Generated by Django 3.1a1 on 2024-09-14 12:37

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_auto_20240914_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ManyToManyField(blank=True, null=True, to='inventario.Continent'),
        ),
        migrations.AlterField(
            model_name='historicalmedicamento',
            name='nueva_forma_farmaceutica',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='nueva_via_administracion', chained_model_field='via_administracion', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.forma_farmaceutica'),
        ),
        migrations.AlterField(
            model_name='location',
            name='new_country',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='new_continent', chained_model_field='continent', on_delete=django.db.models.deletion.CASCADE, to='inventario.country'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='nueva_forma_farmaceutica',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='nueva_via_administracion', chained_model_field='via_administracion', on_delete=django.db.models.deletion.CASCADE, to='inventario.forma_farmaceutica'),
        ),
    ]
