# Generated by Django 5.0.2 on 2024-06-12 00:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("1", "Admin"), ("2", "Operativo"), ("3", "Técnico")],
                        default=None,
                        max_length=100,
                    ),
                ),
                (
                    "lugar",
                    models.CharField(
                        choices=[
                            ("1", "Bogotá"),
                            ("2", "Barranquilla"),
                            ("3", "Medellín"),
                            ("4", "Colombia"),
                        ],
                        default=None,
                        max_length=100,
                    ),
                ),
                ("identidad", models.CharField(blank=True, max_length=100)),
                ("realiza_servicio", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateField(default=datetime.datetime.now)),
                (
                    "image_profile",
                    models.ImageField(
                        default="static/img/user_default.png", upload_to="static/img/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
