# Generated by Django 5.0.2 on 2024-06-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="lugar",
            field=models.CharField(
                choices=[
                    ("Bogotá", "Bogotá"),
                    ("Barranquilla", "Barranquilla"),
                    ("Medellín", "Medellín"),
                    ("Colombia", "Colombia"),
                ],
                default=None,
                max_length=100,
            ),
        ),
    ]
