# Generated by Django 5.0.2 on 2024-06-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_alter_userprofile_lugar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="cambio_ciudad",
            field=models.BooleanField(default=False),
        ),
    ]
